#!/bin/bash

if [ ! -f "python3.12.3-cp312-cp312-manylinux_2_28_x86_64.AppImage" ]; then
    wget https://github.com/niess/python-appimage/releases/download/python3.12/python3.12.3-cp312-cp312-manylinux_2_28_x86_64.AppImage
fi

if [ -d squashfs-root ]; then
    rm -rf squashfs-root
fi

chmod +x python3.12.3-cp312-cp312-manylinux_2_28_x86_64.AppImage
./python3.12.3-cp312-cp312-manylinux_2_28_x86_64.AppImage --appimage-extract

APPDIR="$PWD/squashfs-root"

./squashfs-root/AppRun -m pip install -U pip
./squashfs-root/AppRun -m pip install '.[zim,js]'

rm -f squashfs-root/AppRun
cp AppImage/AppRun ./squashfs-root/usr/bin/levior-run

pushd $APPDIR
ln -s usr/bin/levior-run AppRun
popd

rm squashfs-root/usr/share/applications/python3.12.*.desktop
rm squashfs-root/usr/share/metainfo/*.appdata.xml
mkdir -p squashfs-root/usr/share/metainfo
mkdir -p squashfs-root/usr/share/icons/hicolor/512x512/apps
rm squashfs-root/*.desktop

cp AppImage/io.gitlab.levior.desktop $APPDIR/usr/share/applications
cp AppImage/io.gitlab.levior.desktop $APPDIR/io.gitlab.levior.desktop
cp AppImage/io.gitlab.levior.appdata.xml $APPDIR/usr/share/metainfo
cp media/img/levior.png $APPDIR/io.gitlab.levior.png
cp media/img/levior.png $APPDIR/usr/share/icons/hicolor/512x512/apps

# cleanup
rm -rf squashfs-root/opt/python3.12/include
rm -rf squashfs-root/opt/python3.12/bin/rst*
rm -rf squashfs-root/opt/python3.12/lib/python3.12/ctypes/test
rm -rf squashfs-root/opt/python3.12/lib/python3.12/distutils/tests
rm -rf squashfs-root/opt/python3.12/lib/python3.12/idlelib
rm -rf squashfs-root/opt/python3.12/lib/python3.12/lib2to3
rm -rf squashfs-root/opt/python3.12/lib/python3.12/ensurepip
rm -rf squashfs-root/opt/python3.12/lib/python3.12/tkinter
rm -rf squashfs-root/opt/python3.12/lib/python3.12/site-packages/bs4/tests
rm -rf squashfs-root/opt/python3.12/lib/python3.12/site-packages/pip
rm -rf squashfs-root/opt/python3.12/lib/python3.12/site-packages/setuptools
rm -rf squashfs-root/usr/share/tcltk
rm -rf squashfs-root/usr/lib/libtk*
rm -rf squashfs-root/usr/lib/libtcl*
find squashfs-root | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf

sed -i -e 's/#\!\/.*$/#!\/opt\/python3.12\/bin\/python3.12/' \
    squashfs-root/opt/python3.12/bin/levior

find $APPDIR -type d -exec chmod -v 755 {} \;

export VERSION=$(cat squashfs-root/opt/python3.12/lib/python3.12/site-packages/levior-*.dist-info/METADATA | grep "^Version:.*" | cut -d " " -f 2)

if [ ! -f "appimagetool-x86_64.AppImage" ]; then
    wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
fi

chmod +x appimagetool*.AppImage

ARCH=x86_64 ./appimagetool-x86_64.AppImage squashfs-root/
