#!/bin/bash

if [ ! -f "python3.9.13-cp39-cp39-manylinux2010_x86_64.AppImage" ]; then
    wget https://github.com/niess/python-appimage/releases/download/python3.9/python3.9.13-cp39-cp39-manylinux2010_x86_64.AppImage
fi

if [ -d squashfs-root ]; then
    rm -rf squashfs-root
fi

# Extract this AppImage
chmod +x python*-manylinux2010_x86_64.AppImage
./python*-manylinux2010_x86_64.AppImage --appimage-extract

APPDIR="$PWD/squashfs-root"

./squashfs-root/AppRun -m pip install -U pip
./squashfs-root/AppRun -m pip install '.[zim]'

rm -f squashfs-root/AppRun
cp AppImage/AppRun ./squashfs-root/AppRun
chmod 0755 $APPDIR
chmod 0755 $APPDIR/AppRun

rm squashfs-root/usr/share/applications/python3.9.*.desktop
rm squashfs-root/usr/share/metainfo/*.appdata.xml
mkdir -p squashfs-root/usr/share/metainfo
rm squashfs-root/*.desktop

cp AppImage/io.gitlab.levior.desktop $APPDIR/usr/share/applications
cp AppImage/io.gitlab.levior.desktop $APPDIR/io.gitlab.levior.desktop
cp AppImage/io.gitlab.levior.appdata.xml $APPDIR/usr/share/metainfo
cp media/img/levior.png $APPDIR/io.gitlab.levior.png
cp media/img/levior.png $APPDIR/usr/share/icons/hicolor/512x512/apps

# cleanup
rm -rf squashfs-root/opt/python3.9/include
rm -rf squashfs-root/opt/python3.9/bin/rst*
rm -rf squashfs-root/opt/python3.9/lib/python3.9/ctypes/test
rm -rf squashfs-root/opt/python3.9/lib/python3.9/distutils/tests
rm -rf squashfs-root/opt/python3.9/lib/python3.9/idlelib
rm -rf squashfs-root/opt/python3.9/lib/python3.9/lib2to3
rm -rf squashfs-root/opt/python3.9/lib/python3.9/ensurepip
rm -rf squashfs-root/opt/python3.9/lib/python3.9/tkinter
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/lxml
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/bs4/tests
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/pip
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/setuptools
rm -rf squashfs-root/usr/share/tcltk
rm -rf squashfs-root/usr/lib/libtk*
rm -rf squashfs-root/usr/lib/libtcl*
find squashfs-root | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf

sed -i -e 's/#\!\/.*$/#!\/opt\/python3.9\/bin\/python3.9/' \
    squashfs-root/opt/python3.9/bin/levior

export VERSION=$(cat squashfs-root/opt/python3.9/lib/python3.9/site-packages/levior-*.dist-info/METADATA | grep "^Version:.*" | cut -d " " -f 2)

if [ ! -f "appimagetool-x86_64.AppImage" ]; then
    wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
fi

chmod +x appimagetool*.AppImage

./appimagetool-x86_64.AppImage squashfs-root/
