#!/bin/bash

APPIMAGE_PATH="levior-${VERSION}-x86_64.AppImage"
APPDIR=./appdir
APPIPIP=$APPDIR/usr/bin/pip

MINICONDA_DIST="Miniconda3-py39_23.5.2-0-Linux-x86_64.sh"
curl -o ${MINICONDA_DIST} "https://repo.anaconda.com/miniconda/${MINICONDA_DIST}"

mkdir -p ${APPDIR}/usr
bash ${MINICONDA_DIST} -b -p "${APPDIR}"/usr -f

mkdir -p $APPDIR/usr/share/applications
mkdir -p $APPDIR/usr/share/licenses/levior
mkdir -p $APPDIR/usr/share/metainfo
mkdir -p $APPDIR/usr/share/icons/hicolor/512x512/apps

cp AppImage/levior.desktop $APPDIR/usr/share/applications
cp AppImage/levior.desktop $APPDIR
cp AppImage/levior.appdata.xml $APPDIR/usr/share/metainfo
cp media/img/levior.png $APPDIR
cp media/img/levior.png $APPDIR/io.gitlab.levior.png
cp media/img/levior.png $APPDIR/usr/share/icons/hicolor/512x512/apps

export PATH="$PATH:$APPDIR/usr/bin"

# Enter the venv
. "$APPDIR"/usr/bin/activate

$APPIPIP install --upgrade pip
$APPIPIP install -U --force-reinstall dist/levior-${VERSION}-py3-none-any.whl'[zim]'

pushd "$APPDIR"/usr
rm -rf pkgs
find -type d -iname '__pycache__' -print0 | xargs -0 rm -r
find -type f -iname '*.a' -print -delete

rm -f bin/x86_64-conda_cos6-linux-gnu-ld
rm -f bin/sqlite*
rm -f bin/openssl*
rn -rf condabin
rm -rf conda-meta/
rm -rf lib/cmake/
rm -rf lib/pkgconfig
rm -rf include/
rm -rf share/{gtk-,}doc
rm -rf bin/tcl*
rm -rf bin/lz*
rm -rf bin/xz*
rm -rf lib/itcl4.2.0
rm -rf lib/libtcl*
rm -rf lib/libtk*
rm -rf lib/tdbcmysql*
rm -rf lib/tk*
rm -rf lib/tcl*
rm -rf lib/libasan*
rm -rf lib/libtsan*
rm -rf lib/liblsan*
rm -rf lib/libncurses*
rm -rf lib/python3.9/turtledemo/
rm -rf lib/python3.9/tkinter/
rm -rf lib/python3.9/lib2to3/
rm -rf lib/python3.9/idlelib
rm -rf lib/python3.9/site-packages/git/test
rm -rf lib/python3.9/site-packages/conda_package_handling
rm -rf lib/python3.9/ensurepip
rm -rf lib/python3.9/site-packages/{conda,conda_env}
rm -rf lib/python3.9/site-packages/{setuptools,pip,lib2to3,wheel}
rm -rf lib/python3.9/site-packages/{bs4,distutils}/tests
rm -rf lib/python3.9/idlelib
rm -rf lib/python3.9/pycparser
rm -rf lib/python3.9/tests
rm -rf share/licenses/{gcc-libs,libstdc++}
rm -rf share/man
rm -rf share/readline
rm -rf share/terminfo
rm -rf share/zoneinfo
rm -rf share/info
rm -rf ssl/man
rm -f lib/libstdc++*
popd

cp AppImage/AppRun $APPDIR/AppRun
chmod 755 $APPDIR/AppRun

sed -i -e 's/#\!\/.*$/#!\/usr\/bin\/python3/' $APPDIR/usr/bin/levior

wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool*.AppImage

echo "AppDir successfully created, running appimagetool: $APPIMAGE_PATH"
ARCH=x86_64 ./appimagetool-x86_64.AppImage -n $APPDIR $APPIMAGE_PATH
