#
# France TV Info
# Rules for francetvinfo.fr
#

rules:
  # Aggregate some of the main francetvinfo RSS feeds into one gemlog,
  # accessible from a unique gemini URL
  - url: '^gemini://localhost/ftvinfo'
    type: 'feeds_aggregator'

    feeds:
      https://www.francetvinfo.fr/titres.rss: {}
      https://www.francetvinfo.fr/monde.rss: {}
      https://www.francetvinfo.fr/culture.rss: {}
      https://www.francetvinfo.fr/decouverte.rss: {}
      https://www.francetvinfo.fr/sports.rss: {}
      https://www.francetvinfo.fr/france.rss: {}

  - url: '^https?://[\\w.-]*francetvinfo.fr'
    gemtext_filters:
      - filter: levior.filters.links:url_remove
        urls:
          - '.*\.(png|jpg|jpeg|webp)$'

      - filter: levior.filters:get_out
        re:
          - '^Partager'
          - '^------'

      - levior.filters:rm_bracketed_digits

      - filter: levior.filters:text_filter
        re:
          - '^Sous-menu'
          - 'Menu'
          - 'Accéder'
          - '^aller'
          - '^participer'
          - "Suivez l'actu"
          - '^tout lire'
