#
# France TV Info
# Rules for francetvinfo.fr
#

rules:
  # Aggregate some of the main francetvinfo RSS feeds into one tinylog,
  # accessible from a unique gemini URL

  - url: '^gemini://[\w\.]+/ftvinfo'
    type: 'feeds_aggregator'

    feeds:
      https://www.francetvinfo.fr/politique.rss:
        enabled: ${oc.select:feeds.politique,false}

      https://www.francetvinfo.fr/societe.rss:
        enabled: ${oc.select:feeds.societe,false}

      https://www.francetvinfo.fr/faits-divers.rss:
        enabled: ${oc.select:feeds.faits-divers,false}

      https://www.francetvinfo.fr/titres.rss:
        show_entry_dates: true
        enabled: ${oc.select:feeds.titres,true}

      https://www.francetvinfo.fr/monde.rss:
        enabled: ${oc.select:feeds.monde,true}

      https://www.francetvinfo.fr/culture.rss:
        enabled: ${oc.select:feeds.culture,true}

      https://www.francetvinfo.fr/decouverte.rss:
        enabled: ${oc.select:feeds.decouverte,false}

      https://www.francetvinfo.fr/sports.rss:
        enabled: ${oc.select:feeds.sports,false}

      https://www.francetvinfo.fr/france.rss:
        enabled: ${oc.select:feeds.france,true}

  - url: '^https?://[\\w.-]*francetvinfo.fr'
    gemtext_filters:
      - filter: levior.filters.links:url_remove
        urls:
          - '.*\.(png|jpg|jpeg|webp)$'

      - filter: levior.filters:get_out
        re:
          - '^Partager'
          - '^------'

      - levior.filters:rm_bracketed_digits

      - filter: levior.filters:text_filter
        re:
          - '^Sous-menu'
          - 'Menu'
          - 'Accéder'
          - '^aller'
          - '^participer'
          - "Suivez l'actu"
          - '^tout lire'
          - 'Nos lives en cours'
          - '^Direct'
