#!/bin/bash

HERE=$(dirname $(readlink -f "${0}"))

export PATH=${HERE}/usr/bin:$PATH
export LD_LIBRARY_PATH=${HERE}/usr/lib:$LD_LIBRARY_PATH
export PYTHONHOME=${HERE}/usr
export PYTHONPATH=$PYTHONPATH:${HERE}/usr/lib/python3.9/site-packages
export SSL_CERT_FILE=${HERE}/usr/lib/python3.9/site-packages/certifi/cacert.pem

"${HERE}"/usr/bin/python "${HERE}"/usr/bin/levior "$@"
