#!/bin/bash

if [ -z "${APPIMAGE}" ]; then
    export ARGV0="$0"
    export APPDIR=$(dirname $(readlink -f -- "$0"))
fi

export PATH="${APPDIR}/opt/python3.12/bin":"${APPDIR}/usr/bin":$PATH
export PYTHONPATH="${APPDIR}/opt/python3.12/lib/python3.12/site-packages":$PYTHONPATH
export SSL_CERT_FILE="${APPDIR}/opt/_internal/certs.pem"

"$APPDIR/opt/python3.12/bin/python3.12" "${APPDIR}/opt/python3.12/bin/levior" "$@"
